services:
  web:
    build: .
    ports: 
      - 8080:8080
    environment:
      - CGO_ENABLED=0
      - POSTGRES_NAME=Test
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_USER=Test
      - POSTGRES_PASSWORD=password
    volumes:
      - .:/app
    working_dir: /app/scooter-prj
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgis/postgis:18-3.6
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_NAME=Test
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_USER=Test
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

volumes:
  postgres_data:
