services:
  web:
    build: .
    ports: 
      - 8080:8080
    env_file: ".env"
    volumes:
      - .:/app
    working_dir: /app/scooter-prj
    command: air --build.cmd "go build -o ./tmp/main ./cmd/api/main.go" --build.bin "./tmp/main"
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgis/postgis:18-3.6
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file: ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d scooter_db"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

volumes:
  postgres_data:
